# Web Search Agent
search_engine: "google" # "bing"
search_top_k: 10
search_region: "us"
search_lang: "en"
page_view_port_size: 1024*40
serper_api_key: "6416b97a97ab15ac67883dfbd7bff30c9769d42d"

reading_agent_model: "qwen-plus"

azure_bing_search_subscription_key: "key here if you use azure bing"
azure_bing_search_mkt: "zh-CN" # "en-US"

query_save_path: "./scrl/handler/cache/search_result.json"

server_url_list:
  - "http://localhost:5000"
  - "http://xxx:5000"
